# Generated by Django 5.2.7 on 2025-10-17 12:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=500)),
                ('reason', models.CharField(choices=[('low_confidence', 'Low confidence score'), ('multiple_matches', 'Multiple matches'), ('user_report', 'User reported issue'), ('unknown', 'Unknown species')], max_length=50)),
                ('confidence', models.FloatField()),
                ('submitted_by', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, max_length=500)),
                ('tags', models.JSONField(default=list)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('care_instructions', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plant_species/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plant Species',
                'verbose_name_plural': 'Plant Species',
                'ordering': ['common_name'],
            },
        ),
        migrations.CreateModel(
            name='PlantIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plant_identifications/%Y/%m/%d/')),
                ('predicted_name', models.CharField(max_length=200)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_identifications', to=settings.AUTH_USER_MODEL)),
                ('identified_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plant.plantspecies')),
            ],
            options={
                'verbose_name': 'Plant Identification',
                'verbose_name_plural': 'Plant Identifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPlantCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('plant_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.plantspecies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_collection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
                'unique_together': {('user', 'plant_species')},
            },
        ),
    ]
