# Generated by Django 5.2.5 on 2025-08-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_identifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SavedPlant',
        ),
    ]
