# Generated by Django 5.2.6 on 2025-10-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_identifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_id', models.IntegerField(unique=True)),
                ('common_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('confidence', models.FloatField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('medical_use', models.TextField(blank=True, null=True)),
                ('culinary_use', models.TextField(blank=True, null=True)),
                ('cultural_significance', models.TextField(blank=True, null=True)),
                ('safety_toxicity', models.TextField(blank=True, null=True)),
                ('ecological_role', models.TextField(blank=True, null=True)),
                ('cultivation_tips', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SavedPlant',
        ),
    ]
