# Generated by Django 5.2.6 on 2025-10-08 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_identifier', '0002_plant_delete_savedplant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_id', models.IntegerField(unique=True)),
                ('common_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('confidence', models.FloatField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('medical_use', models.TextField(blank=True, null=True)),
                ('culinary_use', models.TextField(blank=True, null=True)),
                ('cultural_significance', models.TextField(blank=True, null=True)),
                ('safety_toxicity', models.TextField(blank=True, null=True)),
                ('ecological_role', models.TextField(blank=True, null=True)),
                ('cultivation_tips', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_plants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
