# Generated by Django 5.2.6 on 2025-10-08 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_identifier', '0003_savedplant_delete_plant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedplant',
            name='species_id',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='savedplant',
            constraint=models.UniqueConstraint(fields=('user', 'species_id'), name='unique_species_per_user'),
        ),
    ]
