# Generated by Django 5.1.3 on 2025-10-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_identifier', '0004_alter_savedplant_species_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedplant',
            name='culinary_use',
        ),
        migrations.RemoveField(
            model_name='savedplant',
            name='cultivation_tips',
        ),
        migrations.RemoveField(
            model_name='savedplant',
            name='cultural_significance',
        ),
        migrations.RemoveField(
            model_name='savedplant',
            name='ecological_role',
        ),
        migrations.RemoveField(
            model_name='savedplant',
            name='medical_use',
        ),
        migrations.RemoveField(
            model_name='savedplant',
            name='safety_toxicity',
        ),
        migrations.AlterField(
            model_name='savedplant',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
