# Generated by Django 5.1.3 on 2025-10-10 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_identifier', '0005_remove_savedplant_culinary_use_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_id', models.IntegerField()),
                ('common_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-identified_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'species_id'), name='unique_history_per_user')],
            },
        ),
    ]
