# Generated by Django 5.1.3 on 2025-10-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_identifier', '0006_planthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='planthistory',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
